DROP TABLE IF EXISTS can_care_for;
DROP TABLE IF EXISTS pt_avail_periods;
DROP TABLE IF EXISTS ft_leave_periods;
DROP TABLE IF EXISTS bids;
DROP TABLE IF EXISTS caretakers;
DROP TABLE IF EXISTS pets;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pet_types;

DROP TYPE IF EXISTS user_type;
DROP TYPE IF EXISTS bid_status;
DROP TYPE IF EXISTS gender_type;
DROP TYPE IF EXISTS caretaker_type;
DROP TYPE IF EXISTS transfer_type;
DROP TYPE IF EXISTS payment_type;