-- /* pg_insert_rows.sql will be generated by a script later on */

-- -- Dummy pet_types
INSERT INTO pet_types (pet_type, daily_base_price) VALUES ('Dog', 40);
INSERT INTO pet_types (pet_type, daily_base_price) VALUES ('Cat', 20);
-- INSERT INTO pet_types (pet_type, daily_base_price) VALUES ('Hamster', 15);
-- INSERT INTO pet_types (pet_type, daily_base_price) VALUES ('Parrot', 25);
-- INSERT INTO pet_types (pet_type, daily_base_price) VALUES ('Puppy', 30);

-- -- Some normal users
INSERT INTO users (username, password, email, type, gender, is_pet_owner) 
VALUES ('petown', '$2b$10$pCiWBh2kYSqTqFyzNbRhAeKsVpOo9wZ4fVAlAThLlmun5NQ1j.jEe', 'petown@petcare.com', 'normal', 'male', TRUE);
INSERT INTO users (username, password, email, type, gender) 
VALUES ('caretake', '$2b$10$pCiWBh2kYSqTqFyzNbRhAeKsVpOo9wZ4fVAlAThLlmun5NQ1j.jEe', 'caretake@petcare.com', 'normal', 'male');
INSERT INTO users (username, password, email, type, gender) 
VALUES ('caretake1', '$2b$10$pCiWBh2kYSqTqFyzNbRhAeKsVpOo9wZ4fVAlAThLlmun5NQ1j.jEe', 'caretake1@petcare.com', 'normal', 'male');
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Alex', '123456', 'a@gmail.com', 'normal', 'male', 'amex', 123456, 111, 100.75, false);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Bob', 'ABCDEFG', 'b@gmail.com', 'normal', 'male', 'amex', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Cain', 'ABCDEFG', 'c@gmail.com', 'normal', 'male', 'amex', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('David', 'ABCDEFG', 'd@gmail.com', 'normal', 'male', 'mastercard', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Elly', 'ABCDEFG', 'e@gmail.com', 'normal', 'female', 'mastercard', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Fisher', 'ABCDEFG', 'f@gmail.com', 'normal', 'male', 'amex', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Grimes', 'ABCDEFG', 'g@gmail.com', 'normal', 'female', 'amex', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Henry', '123456', 'h@gmail.com', 'normal', 'male', 'amex', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Ily', '123456', 'i@gmail.com', 'normal', 'female', 'amex', 123456, 112, 00.00, true);
-- INSERT INTO users (username, password, email, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Jeraldine', '123456', 'j@gmail.com', 'normal', 'female', 'amex', 123456, 112, 00.00, true);

-- -- Admins
INSERT INTO users (username, password, email, type, gender) 
VALUES ('admin', '$2b$10$pCiWBh2kYSqTqFyzNbRhAeKsVpOo9wZ4fVAlAThLlmun5NQ1j.jEe', 'admin@admin.com', 'admin', 'male');
-- INSERT INTO users (username, password, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Mr. Boss', '123456', 'admin', 'male', 'goldmex', 9999999, 898, 10000000000.00, false);
-- INSERT INTO users (username, password, type, gender, card_name, card_no, cvv, cash, is_pet_owner) VALUES ('Ms. President', '123456', 'admin', 'female', 'goldmex', 9999999, 898, 10000000000.00, false);

-- -- Caretakers
INSERT INTO caretakers(username, type, approved) VALUES ('caretake', 'full-time', TRUE);
INSERT INTO caretakers(username, type, approved) VALUES ('caretake1', 'full-time', FALSE);
-- INSERT INTO caretakers (username, type, avg_rating, current_pets_number) VALUES ('Alex', 'full-time', 2.3, 2);
-- INSERT INTO caretakers (username, type, avg_rating, current_pets_number) VALUES ('Ily', 'full-time', 1.2, 1);
-- INSERT INTO caretakers (username, type, avg_rating, current_pets_number) VALUES ('Bob', 'part-time', 4.2, 1);
-- INSERT INTO caretakers (username, type, avg_rating, current_pets_number) VALUES ('Elly', 'full-time', 5, 5);
-- INSERT INTO caretakers (username, type, avg_rating, current_pets_number) VALUES ('Fisher', 'part-time', 3, 2);

-- Pet
INSERT INTO pets(owner_uname, pet_name, pet_type) VALUES ('petown', 'Doggy', 'Dog');

-- Bid
INSERT INTO bids(owner_uname, ctaker_uname, pet_name, start_date, end_date, status, payment_method, transfer_type, bid_price)
VALUES ('petown', 'caretake', 'Doggy', '2021-01-17', '2021-01-29', 'pending', 'card', 'delivery', '240');
INSERT INTO bids(owner_uname, ctaker_uname, pet_name, start_date, end_date, status, payment_method, transfer_type, bid_price)
VALUES ('petown', 'caretake', 'Doggy', '2020-12-17', '2020-12-29', 'success', 'card', 'delivery', '1480');
INSERT INTO bids(owner_uname, ctaker_uname, pet_name, start_date, end_date, status, payment_method, transfer_type, bid_price)
VALUES ('petown', 'caretake', 'Doggy', '2020-09-17', '2020-11-10', 'success', 'card', 'delivery', '1100');
INSERT INTO bids(owner_uname, ctaker_uname, pet_name, start_date, end_date, status, payment_method, transfer_type, bid_price)
VALUES ('petown', 'caretake', 'Doggy', '2019-09-17', '2019-11-10', 'success', 'card', 'delivery', '1100');

INSERT INTO can_care_for VALUES ('caretake', 'Dog');
INSERT INTO can_care_for VALUES ('caretake', 'Cat');
INSERT INTO can_care_for VALUES ('caretake1', 'Dog');
INSERT INTO can_care_for VALUES ('caretake1', 'Cat');
